### ISSUE TITLE
Update to database only if value has changed

### ISSUE THREAD

**Issue by shalvin** [jason-edwards/price-visualiser#2]
The data grabber should cache the latest values from the database.
When it scapes the data, it checks the cached value to see if it is different. If it is, then it should save it to the database and update the cached value.
The cached values should be initialised from the database at the start of the script.

**Comment by jason-edwards** [comment]
Prices could potentially (however very unlikely) flatline for a period of time. It is useful, if a high resolution of the stock price is going to be used, that this event is captured. If there is a gap in data, the graphing functionality will be forced to linearly interpolate between data points.

More discussion regarding the advantages of an extremely high data resolution will need to be had.

**Comment by shalvin** [comment]
Ok good point. In that case its probably best to leave it as it is. You're trading space (storage for the data points) for time (to process graphs to allow for flatlining) or vice versa. Either way its not a major thing especially since space isn't an issue right now. Maybe if it needs optimisation later we can come back to this.
